# Generated by Django 5.2.7 on 2025-10-23 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embryo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embryo_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Embrión')),
                ('fertilization_technique', models.CharField(choices=[('IVF', 'FIV - Fertilización In Vitro'), ('ICSI', 'ICSI - Inyección Intracitoplasmática')], max_length=10, verbose_name='Técnica de Fertilización')),
                ('sperm_source', models.CharField(choices=[('PARTNER', 'Pareja'), ('DONOR', 'Donante')], max_length=10, verbose_name='Origen del Esperma')),
                ('quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Calidad (1-5)')),
                ('current_state', models.CharField(choices=[('DEVELOPING', 'En Desarrollo'), ('TRANSFERRED', 'Transferido'), ('CRYOPRESERVED', 'Criopreservado'), ('DISCARDED', 'Descartado')], default='DEVELOPING', max_length=20, verbose_name='Estado Actual')),
                ('pgt_performed', models.BooleanField(default=False, verbose_name='PGT Realizado')),
                ('pgt_result', models.BooleanField(blank=True, null=True, verbose_name='Resultado PGT (OK/No OK)')),
                ('nitrogen_tube', models.CharField(blank=True, max_length=50, verbose_name='Tubo de Nitrógeno')),
                ('rack_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Rack')),
                ('discard_reason', models.TextField(blank=True, verbose_name='Motivo de Descarte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embrión',
                'verbose_name_plural': 'Embriones',
            },
        ),
        migrations.CreateModel(
            name='Oocyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oocyte_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Óvulo')),
                ('initial_state', models.CharField(choices=[('VERY_IMMATURE', 'Muy Inmaduro'), ('IMMATURE', 'Inmaduro'), ('MATURE', 'Maduro'), ('FERTILIZED', 'Fertilizado'), ('DISCARDED', 'Descartado'), ('CRYOPRESERVED', 'Criopreservado')], max_length=20, verbose_name='Estado Inicial')),
                ('current_state', models.CharField(choices=[('VERY_IMMATURE', 'Muy Inmaduro'), ('IMMATURE', 'Inmaduro'), ('MATURE', 'Maduro'), ('FERTILIZED', 'Fertilizado'), ('DISCARDED', 'Descartado'), ('CRYOPRESERVED', 'Criopreservado')], max_length=20, verbose_name='Estado Actual')),
                ('maturation_time', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Maduración (horas)')),
                ('discard_reason', models.TextField(blank=True, verbose_name='Motivo de Descarte')),
                ('nitrogen_tube', models.CharField(blank=True, max_length=50, verbose_name='Tubo de Nitrógeno')),
                ('rack_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Rack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Óvulo',
                'verbose_name_plural': 'Óvulos',
            },
        ),
        migrations.CreateModel(
            name='EmbryoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('performed_date', models.DateField(blank=True, null=True, verbose_name='Fecha Realizada')),
                ('beta_positive', models.BooleanField(blank=True, null=True, verbose_name='Beta Positiva')),
                ('gestational_sac', models.BooleanField(blank=True, null=True, verbose_name='Saco Gestacional')),
                ('clinical_pregnancy', models.BooleanField(blank=True, null=True, verbose_name='Embarazo Clínico')),
                ('live_birth', models.BooleanField(blank=True, null=True, verbose_name='Nacido Vivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embryo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='laboratory.embryo')),
            ],
            options={
                'verbose_name': 'Transferencia de Embrión',
                'verbose_name_plural': 'Transferencias de Embriones',
            },
        ),
        migrations.AddField(
            model_name='embryo',
            name='oocyte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embryo', to='laboratory.oocyte'),
        ),
        migrations.CreateModel(
            name='OocyteStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('to_state', models.CharField(max_length=20, verbose_name='Nuevo Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oocyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='laboratory.oocyte')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Óvulo',
                'verbose_name_plural': 'Historiales de Estado de Óvulos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Puncture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('operating_room', models.CharField(max_length=50, verbose_name='Número de Quirófano')),
                ('complications', models.TextField(blank=True, verbose_name='Complicaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punctures_performed', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puncture', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Punción',
                'verbose_name_plural': 'Punciones',
            },
        ),
        migrations.AddField(
            model_name='oocyte',
            name='puncture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oocytes', to='laboratory.puncture'),
        ),
    ]
