# Generated by Django 5.2.7 on 2025-10-23 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('PREGNANCY', 'Embarazo'), ('OOCYTE_PRESERVATION', 'Preservación de Óvulos'), ('EMBRYO_PRESERVATION', 'Preservación de Embriones')], max_length=30, verbose_name='Objetivo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Vigente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('stimulation_protocol', models.TextField(blank=True, verbose_name='Protocolo de Estimulación')),
                ('medication_type', models.CharField(blank=True, max_length=200, verbose_name='Tipo de Medicación')),
                ('medication_dose', models.CharField(blank=True, max_length=100, verbose_name='Dosis')),
                ('medication_duration', models.CharField(blank=True, max_length=100, verbose_name='Duración')),
                ('oocytes_viable', models.BooleanField(blank=True, null=True, verbose_name='Óvulos Viables')),
                ('sperm_viable', models.BooleanField(blank=True, null=True, verbose_name='Esperma Viable')),
                ('consent_document', models.FileField(blank=True, null=True, upload_to='consents/', verbose_name='Consentimiento Firmado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(choices=[('HORMONAL', 'Hormonal'), ('GYNECOLOGICAL', 'Ginecológico'), ('PRESURGICAL', 'Prequirúrgico'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Estudio')),
                ('study_name', models.CharField(max_length=200, verbose_name='Nombre del Estudio')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='study_results/', verbose_name='Archivo de Resultado')),
                ('result_text', models.TextField(blank=True, verbose_name='Resultado (Texto)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_results', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Resultado de Estudio',
                'verbose_name_plural': 'Resultados de Estudios',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_type', models.CharField(choices=[('PATIENT', 'Paciente'), ('INSURANCE', 'Obra Social')], max_length=20, verbose_name='Pagador')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Adeudado')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='MonitoringDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_days', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Día de Monitoreo',
                'verbose_name_plural': 'Días de Monitoreo',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('STUDY', 'Orden de Estudio'), ('PRESCRIPTION', 'Receta Médica')], max_length=20, verbose_name='Tipo de Orden')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='medical_orders/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_orders', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Orden Médica',
                'verbose_name_plural': 'Órdenes Médicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
