# Generated by Django 5.2.7 on 2025-10-23 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('biological_sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('medical_coverage', models.CharField(blank=True, max_length=100, verbose_name='Cobertura Médica')),
                ('member_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Socio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('biological_sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('genital_background', models.TextField(blank=True, verbose_name='Antecedentes Genitales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Pareja',
                'verbose_name_plural': 'Parejas',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_background', models.TextField(blank=True, verbose_name='Antecedentes Clínicos')),
                ('surgical_background', models.TextField(blank=True, verbose_name='Antecedentes Quirúrgicos')),
                ('personal_background', models.TextField(blank=True, verbose_name='Antecedentes Personales')),
                ('family_background', models.TextField(blank=True, verbose_name='Antecedentes Familiares')),
                ('gynecological_background', models.TextField(blank=True, verbose_name='Antecedentes Ginecológicos')),
                ('physical_exam', models.TextField(blank=True, verbose_name='Examen Físico')),
                ('phenotype', models.TextField(blank=True, verbose_name='Fenotipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
    ]
